import os
import sys
import zipfile
import urllib.request
import subprocess

PROJECT_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
SDK_DIR = os.path.join(PROJECT_ROOT, ".android-sdk")
CMDLINE_DIR = os.path.join(SDK_DIR, "cmdline-tools")
LATEST_DIR = os.path.join(CMDLINE_DIR, "latest")
ZIP_PATH = os.path.join(SDK_DIR, "cmdline-tools.zip")

URL = "https://dl.google.com/android/repository/commandlinetools-win-11076708_latest.zip"

print(f"===================================================")
print(f"ResQMesh AI - Android SDK Setup Script")
print(f"===================================================")
print(f"Target SDK Directory: {SDK_DIR}")

os.makedirs(CMDLINE_DIR, exist_ok=True)

if not os.path.exists(os.path.join(LATEST_DIR, "bin", "sdkmanager.bat")):
    print(f"[1/3] Downloading Android Command Line Tools...")
    def reporthook(count, block_size, total_size):
        percent = int(count * block_size * 100 / total_size)
        sys.stdout.write(f"\rDownloading: {percent}% ({count * block_size} / {total_size} bytes)")
        sys.stdout.flush()

    urllib.request.urlretrieve(URL, ZIP_PATH, reporthook)
    print("\n[1/3] Download complete!")

    print(f"[2/3] Extracting Command Line Tools...")
    temp_extract = os.path.join(SDK_DIR, "temp_extract")
    with zipfile.ZipFile(ZIP_PATH, 'r') as zip_ref:
        zip_ref.extractall(temp_extract)

    os.makedirs(LATEST_DIR, exist_ok=True)
    extracted_cmdline = os.path.join(temp_extract, "cmdline-tools")
    for item in os.listdir(extracted_cmdline):
        src = os.path.join(extracted_cmdline, item)
        dst = os.path.join(LATEST_DIR, item)
        if not os.path.exists(dst):
            os.rename(src, dst)

    os.remove(ZIP_PATH)
    import shutil
    shutil.rmtree(temp_extract, ignore_errors=True)
    print("[2/3] Extraction complete!")

print("[3/3] Installing Android SDK platform-34, build-tools 34.0.0, and platform-tools...")

java_home = os.environ.get("JAVA_HOME", "")
if not java_home or "jdk-22" in java_home:
    user_home = os.path.expanduser("~")
    gradle_jdk = os.path.join(user_home, ".gradle", "jdks", "eclipse_adoptium-17-amd64-windows", "jdk-17.0.20+8")
    if os.path.exists(gradle_jdk):
        os.environ["JAVA_HOME"] = gradle_jdk
        os.environ["PATH"] = os.path.join(gradle_jdk, "bin") + os.pathsep + os.environ.get("PATH", "")

sdkmanager = os.path.join(LATEST_DIR, "bin", "sdkmanager.bat")
cmd = [
    sdkmanager,
    f"--sdk_root={SDK_DIR}",
    "platforms;android-34",
    "build-tools;34.0.0",
    "platform-tools"
]

print(f"Running: {' '.join(cmd)}")
process = subprocess.Popen(
    cmd,
    stdin=subprocess.PIPE,
    stdout=subprocess.PIPE,
    stderr=subprocess.STDOUT,
    text=True
)

stdout, _ = process.communicate(input="y\ny\ny\ny\ny\n")
print(stdout)

local_props = os.path.join(PROJECT_ROOT, "mobile", "android", "local.properties")
escaped_sdk_dir = SDK_DIR.replace("\\", "\\\\").replace(":", "\\:")
with open(local_props, "w") as f:
    f.write(f"# Auto-generated by setup_android_sdk.py\n")
    f.write(f"sdk.dir={escaped_sdk_dir}\n")

print(f"Updated {local_props} with sdk.dir={escaped_sdk_dir}")
print("===================================================")
print("Android SDK Setup Complete!")
print("===================================================")
